name: build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install clang-format
          sudo apt install clang-tidy
      - name: Run clang-format
        run: find . -iname *.hpp -o -iname *.cpp | xargs clang-format --dry-run --Werror -i 
